version: 2

jobs:

  build:
    working_directory: /opt/table-tennis-team-service
    docker:
      - image: hseeberger/scala-sbt:8u141-jdk_2.12.3_0.13.16
    steps:
      - checkout
      - run:
          name: Clean SBT project
          command: sbt clean
      - restore_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}
      - run:
          name: SBT compile
          command: sbt compile
      - save_cache:
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}
      - run:
          name: Run tests
          command: sbt coverage test
      - run:
          name: Create coverage report
          command: sbt coverageReport
      - store_test_results:
          path: target/scala-2.12/scoverage-report